eureka:
  client:
    service-url:
      defaultZone: http://localhost:7761/eureka/
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
    hostname: localhost

finsphere:
  jwt:
    secret: "YourVeryLongSuperSecretKeyForFinSphereNexus2026!!"
    expirationMs: 86400000
  security:
    # 32 characters exactly. No quotes, no spaces.
    encryption-key: F1nSph3r3_N3xu5_S3cur1ty_K3y_026
    # 12 bytes is the NIST recommendation for AES-GCM
    iv-length: 12

spring:
  kafka:
    bootstrap-servers: localhost:7092
  datasource:
    driver-class-name: org.postgresql.Driver
    username: fsn_user
    password: fsn@123

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [${spring.application.name}] %logger{36} - %msg%n"
  level:
    com.finsphere: INFO
    org.apache.kafka: WARN