server:
  port: 7001 # 7000-series

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finsphere_auth
    username: fsn_user
    password: fsn@123 # Use the actual password you set for Postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # Adding this helps Hibernate start even if the connection is slow
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7761/eureka/

finsphere:
    jwt:
      secret: "YourVeryLongSuperSecretKeyForFinSphereNexus2026!!" # Min 32 chars
      expirationMs: 86400000 # 24 Hours