server:
  port: 7001

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/finsphere_auth
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: fsn_identity
  data:
    redis:
      host: localhost
      port: 7379