server:
  port: 7002

spring:
  application:
    name: chit-schemes-management-service

  datasource:
    url: jdbc:postgresql://localhost:5432/finsphere_chit
    username: fsn_user
    password: fsn@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: fsn_chit_management

  kafka:
    bootstrap-servers: 127.0.0.1:7092
    consumer:
      group-id: chit-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.finsphere.common.*"

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7761/eureka/
    register-with-eureka: true
    fetch-registry: true