server:
  port: 7002

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finsphere_chit
    username: fsn_user
    password: fsn@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Good for early development
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: fsn_chit_management

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7761/eureka/