server:
  port: 7002

spring:
  application:
    name: chit-finance-service

  datasource:
    url: jdbc:postgresql://localhost:5432/finsphere_chit_finance
    # Note: username/password/driver are now inherited from application.yml

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: fsn_finance

  data:
    mongodb:
      uri: mongodb://localhost:17017/finsphere_transaction
      auto-index-creation: true

  kafka:
    # We keep the consumer config here because it is unique to this service
    consumer:
      group-id: chit-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.finsphere.common.*"