server:
  port: 7000
  forward-headers-strategy: framework

spring:
  application:
    name: frontend-service
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  resources:
    static-locations: classpath:/static/

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:7761/eureka/