server:
  port: 7070

spring:
  cloud:
    gateway:
      routes:
        # Route for Login/Register
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        # Route for Chit Fund Logic
        - id: chit-service
          uri: lb://chit-logic-service
          predicates:
            - Path=/chits/**

        # Route for Daily Finance/Loans
        - id: lending-service
          uri: lb://lending-service
          predicates:
            - Path=/loans/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7761/eureka/