server:
  port: 7888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          # Try removing one slash or using the ${user.home} shortcut
          uri: file://${user.home}/personal_workspace/FinSphere-Nexus/config-repo
          default-label: infra-conf
          # Add this to bypass strict Git host checking locally
          clone-on-start: true